<?php

$config = new PhpCsFixer\Config();
return $config
	->setRiskyAllowed(true)
	->setRules([
		'align_multiline_comment' => true,
		'array_indentation' => true,
		'assign_null_coalescing_to_coalesce_equal' => true,
		'binary_operator_spaces' => [
			'operators' => [
				'&' => 'no_space',
				'|' => 'no_space',
			],
		],
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
		'braces' => [
			'allow_single_line_anonymous_class_with_empty_body' => true,
			'position_after_functions_and_oop_constructs' => 'same',
		],
		'cast_spaces' => ['space' => 'none'],
		'class_definition' => [
			'multi_line_extends_each_single_line' => true,
		],
		'concat_space' => true,
		'compact_nullable_type_declaration' => true,
		'constant_case' => true,
		'declare_equal_normalize' => ['space' => 'none'],
		'explicit_string_variable' => true,
		'full_opening_tag' => true,
		'function_declaration' => [
			'closure_function_spacing' => 'none',
			'closure_fn_spacing' => 'none',
		],
		'heredoc_indentation' => [
			'indentation' => 'same_as_start',
		],
		'include' => true,
		'indentation_type' => true,
		'integer_literal_case' => true,
		'line_ending' => true,
		'lowercase_cast' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'method_argument_space' => [
			'on_multiline' => 'ensure_fully_multiline',
		],
		'method_chaining_indentation' => true,
		'new_with_braces' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_break_comment' => ['comment_text' => 'FALLTHROUGH'],
		'no_closing_tag' => true,
		'no_empty_statement' => true,
		'no_empty_phpdoc' => true,
		'no_extra_blank_lines' => [
			'tokens' => [
				'break',
				'case',
				'continue',
				'curly_brace_block',
				'default',
				'extra',
				'parenthesis_brace_block',
				'return',
				'square_brace_block',
				'switch',
				'throw',
			],
		],
		'no_leading_import_slash' => true,
		'no_multiple_statements_per_line' => true,
		'no_spaces_after_function_name' => true,
		'no_space_around_double_colon' => true,
		'no_spaces_around_offset' => true,
		'no_spaces_inside_parenthesis' => true,
		'no_trailing_comma_in_singleline' => true,
		'no_unneeded_braces' => true,
		'no_unused_imports' => true,
		'no_useless_concat_operator' => true,
		'no_whitespace_in_blank_line' => true,
		'normalize_index_brace' => true,
		'octal_notation' => true,
		'ordered_attributes' => true,
		'ordered_class_elements' => [
			'order' => [
				'use_trait',
				'constant',
				'property_static',
				'property',
			],
		],
		'ordered_imports' => [
			'imports_order' => [
				'class',
				'function',
				'const',
			],
			'sort_algorithm' => 'alpha',
		],
		'ordered_interfaces' => true,
		'phpdoc_line_span' => [
			'const' => 'single',
			'property' => 'single',
		],
		'phpdoc_trim' => true,
		'php_unit_attributes' => true,
		'php_unit_construct' => true,
		'php_unit_data_provider_static' => true,
		'php_unit_dedicate_assert' => true,
		'php_unit_dedicate_assert_internal_type' => true,
		'php_unit_method_casing' => true,
		'php_unit_strict' => true,
		'return_type_declaration' => ['space_before' => 'none'],
		'single_quote' => true,
		'short_scalar_cast' => true,
		'simple_to_complex_string_variable' => true,
		'single_blank_line_at_eof' => true,
		'single_blank_line_before_namespace' => true,
		'single_class_element_per_statement' => [
			'elements' => [
				'property',
			],
		],
		'single_import_per_statement' => true,
		'single_line_after_imports' => true,
		'single_trait_insert_per_statement' => true,
		'spaces_inside_parentheses' => true,
		'strict_param' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'ternary_operator_spaces' => true,
		'trailing_comma_in_multiline' => [
			'elements' => [
				'arrays',
				'arguments',
			],
		],
		'type_declaration_spaces' => true,
		'types_spaces' => true,
		'visibility_required' => [
			'elements' => [
				'method',
				'property',
			],
		],
	])
	->setIndent("\t");
